### ISSUE TITLE
Can not compile correctly

### ISSUE THREAD

**Issue by HNU-lyx** [rsspp/experiments#7] opened 2021-04-20 06:49 UTC
Hello，sorry to bother you. But I really need your help.
I configure npf , modified my kernel and configure the dpdk binding，and I can run testpmd normally. But I had some problems.
_root@guolab-6:/home/guolab/lyx/experiments/imbalance# make
/home/guolab/lyx/npf/npf-compare.py rsspp+rss:RSS rsspp+sprayer:Sprayer "rsspp+pipeline,queue:Software Shared Queue" "rsspp+pipeline,rr:Software RR Queue" "rsspp+pipeline,flowrr:Software Stateful RR" "rsspp+pipeline,flowrr,AWARE=1:Software Stateful Load" "rsspp+staticmetron:Metron Static" "rsspp+dynamicmetron:Metron Dynamic" "rsspp+pianorss:RSSPP" --testie ../dpdk.testie --cluster client=client0,nic=0 p=server0,nic=0 server=server0,nic=0 dut=server0,nic=0 --output --output-columns x raw  --graph-filename ./imbalance/imbalance-kthmorningsingle  --no-build --config n_runs=1 --variables TIMING=1 QUEUE=8 W=500 --tags kthmorningsingle fnt --max-results "--show-full"
Testing connection to client0...
Testing connection to server0...
[RSS] Running testie dpdk.testie on version f9efb13...
Building FastClick - DPacket and disabled all generally unused features (because could not find /home/guolab/lyx/npf/build/fastclick-light/bin/click)
Configuring 828d726...
Cleaning 828d726...
Building 828d726...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light”
make[2]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/userlevel”
make[2]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/lib”
  CXX ../../lib/string.cc
  CXX ../../lib/glue.cc
  CXX ../../lib/straccum.cc
  CXX ../../lib/bitvector.cc
  CXX ../../lib/hashallocator.cc
  CXX ../../lib/etheraddress.cc
  CXX ../../lib/ipaddress.cc
  CXX ../../lib/timestamp.cc
  CXX ../../lib/error.cc
  CXX elementt.cc
  CXX eclasst.cc
  CXX ../lib/string.cc
Makefile:62: recipe for target 'hashallocator.o' failed
  CXX ../lib/straccum.cc
Makefile:62: recipe for target 'elementt.o' failed
  CXX ../lib/nameinfo.cc
Makefile:62: recipe for target 'straccum.o' failed
  CXX ../lib/bitvector.cc
Makefile:62: recipe for target 'etheraddress.o' failed
Makefile:62: recipe for target 'timestamp.o' failed
  CXX routert.cc
  CXX ../lib/bighashmap_arena.cc
Makefile:62: recipe for target 'glue.o' failed
  CXX ../lib/hashallocator.cc
Makefile:62: recipe for target 'bitvector.o' failed
  CXX ../lib/ipaddress.cc
  CXX runparse.cc
Makefile:62: recipe for target 'ipaddress.o' failed
  CXX ../lib/ipflowid.cc
Makefile:62: recipe for target 'string.o' failed
  CXX ../lib/etheraddress.cc
  CXX ../../lib/variableenv.cc
  CXX landmarkt.cc
Makefile:62: recipe for target 'eclasst.o' failed
  CXX ../lib/packet.cc
  CXX lexert.cc
  CXX ../lib/packetbatch.cc
Makefile:62: recipe for target 'variableenv.o' failed
  CXX ../lib/error.cc
Makefile:62: recipe for target 'landmarkt.o' failed
  CXX ../lib/timestamp.cc
Makefile:62: recipe for target 'runparse.o' failed
  CXX ../lib/glue.cc
  CXX lexertinfo.cc
Makefile:62: recipe for target 'error.o' failed
  CXX ../lib/task.cc
  CXX ../../lib/driver.cc
Makefile:62: recipe for target 'lexertinfo.o' failed
  CXX ../lib/timer.cc
  CXX ../../lib/confparse.cc
  CXX ../../lib/args.cc
  CXX ../../lib/archive.cc
  CXX processingt.cc
Makefile:60: recipe for target 'packet.o' failed
  CXX etraits.cc
Makefile:62: recipe for target 'driver.o' failed
  CXX elementmap.cc
  CXX ../../lib/userutils.cc
Makefile:62: recipe for target 'archive.o' failed
  CXX ../../lib/md5.cc
Makefile:62: recipe for target 'md5.o' failed
  CXX toolutils.cc
Makefile:62: recipe for target 'etraits.o' failed
  CC ../../lib/clp.c
Makefile:62: recipe for target 'routert.o' failed
Makefile:62: recipe for target 'toolutils.o' failed
Makefile:62: recipe for target 'lexert.o' failed
Makefile:62: recipe for target 'userutils.o' failed
Makefile:62: recipe for target 'args.o' failed
make[2]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/userlevel”
Makefile:58: recipe for target 'userlevel' failed
Makefile:53: recipe for target 'clp.o' failed
Makefile:62: recipe for target 'confparse.o' failed
Makefile:62: recipe for target 'elementmap.o' failed
Makefile:62: recipe for target 'processingt.o' failed
  AR libclicktool.a
  RANLIB libclicktool.a
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/lib”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-align”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-check”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-combine”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-devirtualize”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-fastclassifier”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-flatten”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-mkmindriver”
  CXX click-check.cc
  CXX alignment.cc
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-pretty”
  CXX click-combine.cc
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click2xml”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-undead”
make[3]: 进入目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-xform”
  CXX cxxclass.cc
  CXX alignclass.cc
  CXX click-fastclassifier.cc
  CXX click-flatten.cc
  CXX click-mkmindriver.cc
  CXX click2xml.cc
  CXX click-pretty.cc
  CXX click-undead.cc
  CXX adjacency.cc
  CXX html.cc
  LINK click-flatten
  LINK click-check
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-flatten”
  CXX click-xform.cc
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-check”
  CXX click-align.cc
  CXX specializer.cc
  CXX xml2click.cc
  CXX click-uncombine.cc
  CXX signature.cc
  CXX click-devirtualize.cc
  LINK click-undead
  LINK click-combine
  LINK click-xform
  CXX fc_classifier.cc
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-undead”
  CXX fc_ipclassifier.cc
  LINK click-mkmindriver
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-xform”
  LINK click-uncombine
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-mkmindriver”
  LINK click-align
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-combine”
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-align”
  LINK click-fastclassifier
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-fastclassifier”
  LINK click-pretty
  LINK click2xml
  LINK xml2click
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-pretty”
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click2xml”
  LINK click-devirtualize
make[3]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools/click-devirtualize”
make[2]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light/tools”
make[1]: 离开目录“/home/guolab/lyx/npf/build/fastclick-light”

stderr :
make[3]: [hashallocator.o] Error 1 (已忽略）
make[3]: [elementt.o] Error 1 (已忽略）
make[3]: [straccum.o] Error 1 (已忽略）
make[3]: [etheraddress.o] Error 1 (已忽略）
make[3]: [timestamp.o] Error 1 (已忽略）
make[3]: [glue.o] Error 1 (已忽略）
make[3]: [bitvector.o] Error 1 (已忽略）
make[3]: [ipaddress.o] Error 1 (已忽略）
make[3]: [string.o] Error 1 (已忽略）
make[3]: [eclasst.o] Error 1 (已忽略）
make[3]: [variableenv.o] Error 1 (已忽略）
make[3]: [landmarkt.o] Error 1 (已忽略）
make[3]: [runparse.o] Error 1 (已忽略）
make[3]: [error.o] Error 1 (已忽略）
make[3]: [lexertinfo.o] Error 1 (已忽略）
In file included from ../lib/packet.cc:35:0:
../include/click/dpdkdevice.hh: In member function ‘void DPDKDevice::set_isolation_mode(const bool&)’:
../include/click/dpdkdevice.hh:190:13: error: ‘rte_flow_isolate’ was not declared in this scope
             rte_flow_isolate(port_id, 1, 0);
             ^~~~~~~~~~~~~~~~
../include/click/dpdkdevice.hh:190:13: note: suggested alternative: ‘set_init_flow_isolate’
             rte_flow_isolate(port_id, 1, 0);
             ^~~~~~~~~~~~~~~~
             set_init_flow_isolate
../include/click/dpdkdevice.hh:192:13: error: ‘rte_flow_isolate’ was not declared in this scope
             rte_flow_isolate(port_id, 0, 0);
             ^~~~~~~~~~~~~~~~
../include/click/dpdkdevice.hh:192:13: note: suggested alternative: ‘set_init_flow_isolate’
             rte_flow_isolate(port_id, 0, 0);
             ^~~~~~~~~~~~~~~~
             set_init_flow_isolate
make[2]: *** [packet.o] Error 1
make[2]: *** 正在等待未完成的任务....
make[3]: [driver.o] Error 1 (已忽略）
make[3]: [archive.o] Error 1 (已忽略）
make[3]: [md5.o] Error 1 (已忽略）
make[3]: [etraits.o] Error 1 (已忽略）
make[3]: [routert.o] Error 1 (已忽略）
make[3]: [toolutils.o] Error 1 (已忽略）
make[3]: [lexert.o] Error 1 (已忽略）
make[3]: [userutils.o] Error 1 (已忽略）
make[3]: [args.o] Error 1 (已忽略）
make[1]: *** [userlevel] Error 2
make[1]: *** 正在等待未完成的任务....
make[3]: [clp.o] Error 1 (已忽略）
make[3]: [confparse.o] Error 1 (已忽略）
make[3]: [elementmap.o] Error 1 (已忽略）
make[3]: [processingt.o] Error 1 (已忽略）
ar: `u' 修饰符被忽略，因为 `D' 为默认（参见 `U'）

Compilation of FastClick - DPacket and disabled all generally unused features FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/fastclick-light
Traceback (most recent call last):
  File "/home/guolab/lyx/npf/npf-compare.py", line 196, in <module>
    main()
  File "/home/guolab/lyx/npf/npf-compare.py", line 191, in main
    series, time_series = comparator.run(testie_name=args.testie, tags=args.tags, options=args, on_finish=lambda series,time_series:do_graph(filename,args,series,time_series,options=args) if args.iterative else None)
  File "/home/guolab/lyx/npf/npf-compare.py", line 35, in run
    build, data_dataset, kind_dataset  = regressor.regress_all_testies(testies=[testie], options=options, on_finish=lambda b,dd,td: self.build_list(on_finish,testie,b,dd,td) if on_finish else None,iserie=irepo,nseries=len(self.repo_list) )
  File "/home/guolab/lyx/npf/npf/regression.py", line 166, in regress_all_testies
    do_test=options.do_test, on_finish=early_results, iserie=iserie*len(testies) + itestie,nseries=len(testies)*nseries)
  File "/home/guolab/lyx/npf/npf/testie.py", line 1131, in execute_all
    v_internals=v_internals)
  File "/home/guolab/lyx/npf/npf/testie.py", line 928, in do_init_all
    if not self.build_deps([build.repo], v_internals=v_internals, no_build=options.no_build):
  File "/home/guolab/lyx/npf/npf/testie.py", line 270, in build_deps
    imp.testie.build_deps(repo_under_test, v_internals, True, done=done)
  File "/home/guolab/lyx/npf/npf/testie.py", line 267, in build_deps
    raise Exception("Could not build dependency %s" % dep)
Exception: Could not build dependency fastclick-light
Makefile:20: recipe for target 'single' failed
make: *** [single] Error 1_

Can you give me some help? Thanks.

**Comment by tbarbette** [comment] 2021-04-20 17:34
You're running an old version of RSS++, can you remove  " --no-build " from the Makefile?

**Comment by GitHub-sc-lyx** [comment] 2021-04-22 12:37
After I revised it, there was still a problem.
It seems that it is still in the process of compilation.

root@guolab-6:/home/guolab/lyx/experiments/drop# make
/home/guolab/lyx/npf/npf-compare.py "rsspp+rss:RSS" rsspp+sprayer:Sprayer "rsspp+pipeline,queue:Software Shared Queue" "rsspp+pipeline,rr:Software RR Queue" "rsspp+pipeline,flowrr:Software Stateful RR" "rsspp+pipeline,flowrr,AWARE=1:Software Stateful Load" "rsspp+pipeline,queue:Software Shared Queue" "rsspp+dynamicmetron:Metron Dynamic" "rsspp+pianorss:RSSPP" --testie ../dpdk.testie --cluster client=client0,nic=0 server=server0,nic=0 --variables "QUEUE=[1-16]" --show-full --output --output-columns x raw --graph-filename drop-kthmorningquad/.pdf --tags kthmorningquad  --graph-size 6 3.5 --config n_runs=3 --variables TIMING=0 W=300 FREQ=1000 --result-path ".npf_results" "--show-full"
Testing connection to client0...
Testing connection to server0...
WARNING : FREQ does not override anything
[RSS] Running testie dpdk.testie on version 8cfa260...
Building RSS (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of RSS FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
WARNING : FREQ does not override anything
[Sprayer] Running testie dpdk.testie on version 8cfa260...
Building Sprayer (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of Sprayer FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
WARNING : FREQ does not override anything
[Software Shared Queue] Running testie dpdk.testie on version 8cfa260...
Building Software Shared Queue (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of Software Shared Queue FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
WARNING : FREQ does not override anything
[Software RR Queue] Running testie dpdk.testie on version 8cfa260...
Building Software RR Queue (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of Software RR Queue FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
WARNING : FREQ does not override anything
[Software Stateful RR] Running testie dpdk.testie on version 8cfa260...
Building Software Stateful RR (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of Software Stateful RR FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
WARNING : FREQ does not override anything
[Software Stateful Load] Running testie dpdk.testie on version 8cfa260...
Building Software Stateful Load (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of Software Stateful Load FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
WARNING : FREQ does not override anything
[Software Shared Queue] Running testie dpdk.testie on version 8cfa260...
Building Software Shared Queue (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of Software Shared Queue FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
WARNING : FREQ does not override anything
[Metron Dynamic] Running testie dpdk.testie on version 8cfa260...
Building Metron Dynamic (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of Metron Dynamic FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
WARNING : FREQ does not override anything
[RSSPP] Running testie dpdk.testie on version 8cfa260...
Building RSSPP (because could not find /home/guolab/lyx/npf/build/rsspp/bin/click)
This will take a while to compile because parallel compilation has to be disabled to broken dependency in Click
Configuring 8cfa260...
Cleaning 8cfa260...
Building 8cfa260...
Aborted (error code 2) !
stdout :
make[1]: 进入目录“/home/guolab/lyx/npf/build/rsspp”
make[2]: 进入目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
  FINDELEMENTS elements.conf
  CREATE elements.mk
make[2]: 离开目录“/home/guolab/lyx/npf/build/rsspp/userlevel”
Makefile:57: recipe for target 'userlevel' failed
make[1]: 离开目录“/home/guolab/lyx/npf/build/rsspp”

stderr :
make[2]: *** 没有规则可制作目标“.sentinel”，由“click” 需求。 停止。
make[1]: *** [userlevel] Error 2

Compilation of RSSPP FAILED. Check the log above, or look at the source at /home/guolab/lyx/npf/build/rsspp
No valid tags/testie/repo combination.
python3 plot.py
Unable to init server: Could not connect: Connection refused
Unable to init server: 无法连接： Connection refused

(plot.py:39924): Gdk-CRITICAL **: 17:16:59.150: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Plotting tail latency according to load
Reading trace kthmorningquad
/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
Reading trace kthmorningquad-fw
/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)

**Comment by tbarbette** [comment] 2021-04-22 14:26
Can you go to /home/guolab/lyx/npf/build/rsspp/ and do `git pull ;  make V=1` ?

**Comment by tbarbette** [comment] 2021-04-22 14:27
And if it does not work make clean then try again? So we don't ping pong for that one :) thanks!

**Comment by GitHub-sc-lyx** [comment] 2021-04-27 16:23
Thanks, but it doesn't work.

> root@guolab-6:/home/guolab/lyx/npf/build/rsspp# make V=1
> make[1]: Entering directory '/home/guolab/lyx/npf/build/rsspp/userlevel'
> echo "userlevel  analysis app aqm ethernet etherswitch flow icmp ids ip json local research simple standard tcpudp test threads" | ../bin/click-buildtool findelem -r userlevel -p .. -X ./elements.exclude --checksum elements.csmk > elements.conf
> ../bin/click-buildtool elem2make -x "addressinfo.o alignmentinfo.o errorelement.o portinfo.o scheduleinfo.o" < elements.conf > elements.mk
> make[1]: *** No rule to make target '.sentinel', needed by 'click'.  Stop.
> make[1]: Leaving directory '/home/guolab/lyx/npf/build/rsspp/userlevel'
> Makefile:57: recipe for target 'userlevel' failed
> make: *** [userlevel] Error 2
> root@guolab-6:/home/guolab/lyx/npf/build/rsspp# 

It seems that rsspp is not complete. But when i git pull , it looks okay .

> root@guolab-6:/home/guolab/lyx/npf/build/rsspp# git pull
> warning: redirecting to https://github.com/rsspp/fastclick.git/
> Already up to date.
> root@guolab-6:/home/guolab/lyx/npf/build/rsspp#

I think I need to show my environment to you.

### 1. npf       
path:/home/guolab/lyx/npf
I cloned npf and ran iperf3 successfully.

cluster/server0.node:

> addr=server0  (I have defined server0 and client0 in /etc/hosts)
> path=/home/guolab/lyx/npf
> user=root
> nfs=0
> 
> 0:ifname=enp65s0
> 0:mac=00:02:c9:05:6a:81
> 0:pci=0000:41:00.0
> 0:ip=192.168.31.6

cluster/client0.node:

> addr=client0
> path=/home/guolab/lyx/npf
> user=root
> nfs=0
> 
> 0:ifname=enp65s0
> 0:mac=00:02:c9:05:6a:41
> 0:pci=0000:41:00.0
> 0:ip=192.168.31.7

### 2. Makefiles configuration
Set NPF_PATH=/home/guolab/lyx/npf

### 3. Modified Kernel on the DUT
I did what readme did.

### 4. Install DPDK on both machines
I installed dpdk19.02 on both server and client, and I can use testpmd normally.

after this ,  all I have to do is "make single" under the corresponding folder on the server side.
I noticed that there is only rsspp under the build folder of npf now.

But before update, I remember that there are also fastclick-light and iperf-rsspp.

Thank you again for taking the time to look at my issue and answer it.

**Comment by tbarbette** [comment] 2021-04-30 08:01
`make[1]: *** No rule to make target '.sentinel', needed by 'click'. Stop.`
That's a compilation problem and indeed RSS++ (FastClick) is not compiled correctly.

Do you have RTE_SDK set correctly? You used the archive of 19.02 from dpdk.org, not lts? I'll try myself that specific version :)

**Comment by GitHub-sc-lyx** [comment] 2021-04-30 08:05
RTE_SDK set up correctly , and I did use 19.02 from dpdk.org which in your README.

**Comment by tbarbette** [comment] 2021-05-03 13:24
It should be fixed now. You can pull this repository and it will also update rss++ through NPF. I did the last merge too fast.

I actually migrated this repository to the mainline Click so this repository is only to reproduce experiments, for the features one can look at FastClick directly

**Closed as completed** 2024-05-21 11:39 UTC
