### ISSUE TITLE
Can not set up imbalance experiment properly

### ISSUE THREAD

**Issue by zli19** [rsspp/experiments#1] opened 2020-04-15 17:09 UTC
After I configure the dpdk binding, server0.node, client0.node, and set up sshfs sharing of npf folder between two computers. I encounter below problem(the computer have 24 logical cores):
$ make allsingle
/home/zli/npf//npf-compare.py "rsspp+rss:RSS" rsspp+sprayer:Sprayer "rsspp+pipeline,queue:Software Shared Queue" "rsspp+pipeline,rr:Software RR Queue" "rsspp+pipeline,flowrr:Software Stateful RR" "rsspp+pipeline,flowrr,AWARE=1:Software Stateful Load" "rsspp+dynamicmetron:Metron Dynamic" "rsspp+pianorss:RSSPP" --testie ../dpdk.testie --cluster client=client0,nic=0 p=server0,nic=0 server=server0,nic=0 --variables "QUEUE=[1-24]" --show-full --output --output-columns x raw --graph-filename ./imbalance/imbalance-all-kthmorningsingle.pdf --tags kthmorningsingle --no-build --graph-size 6 3.5 --config "graph_y_group={result:all}" n_runs=3 --variables TIMING=1 WBASE=1000 --tags fnt dynaw --no-graph --result-path ".npf_results_kthmorningsingle" --max-results
Testing connection to nimbnode17...
Testing connection to nimbnode18...
WARNING : WBASE does not override anything
[RSS] Running testie dpdk.testie on version bef6413...
SyntaxError
   int( (1000 / 8) * $QUEUE)
Syntax Error
SyntaxError
   "0" if 23 >= $QUEUE else "1"
Syntax Error
Executing init scripts...
SyntaxError
   int( (1000 / 8) * $QUEUE)
Syntax Error
SyntaxError
   "0" if 23 >= $QUEUE else "1"
Syntax Error
BLOCKING = 0, BTHREAD = 34, GEN_NOREWRITE_ETHER = 1, LINUX_PATH = ~/workspace/linux-5.1/, MONTHREAD = 35, NDESC = 4096, PAUSE = none, PIPELINE = 0, REPORT_PERIOD = 1, SINGLEDESC = 4096, END_AFTER = 0, FORCE_LEN = 0, RX_PORT = 80, SCRIPT_ELEMENT = s, STOP_AT_TRACE = 0, fw_rules_file = /includes/ipfilter/morning-single-rules-20000.rules, trace = /home/zli/traces/maccdc2011_00013_20110312202724.pcap, CLIENT_NIC = 0, GEN_DESC = 4096, GEN_RATE = -1, GEN_THREADS = 4, IGNORE = 0, ITERATION_TIME = 0, LATENCYDUMP = /tmp/latency.csv, LIMIT = 200000000, LIMIT_TIME = 70, NIC = 0, PKTGEN_BURST_OUT = 32, PROMISC = true, R4 = 15, RCV_NIC = 0, AUTOSCALE = false, BALANCE_PERIOD = 500, CYCLES = cycles, DOMARK = true, FMARK = true, HAVE_TIMING_FNT = 2, METRONTARGET = load, QUEUE = 1, RETA_SIZE = 512, TARGETMETHOD = rss, TIMING = 1, VMARK = true, WBASE = 1000 [run 1/3 for test 1/24]
p [0] bash: line 2: cd: /home/zli/workspace/linux-5.1/tools/power/cpupower/: No such file or directory
MainClickDUT Launching client RSS_IO rx-none.click rx-process.click PARALLEL_PROCESSER DEV_READ
MainClickDUT click: no process found
MainClickDUT
MainClickDUT DPDKInfo(100000);
MainClickDUT define(
MainClickDUT $iface      0000:03:00.0,
MainClickDUT     $dispatcherNb 1,
MainClickDUT $numa       false,
MainClickDUT $verbose    99,
MainClickDUT     $npf_root   ../../experiments
MainClickDUT );
MainClickDUT
MainClickDUT elementclass Pipeline {
MainClickDUT
MainClickDUT     input
MainClickDUT     -> wp :: WorkPackage(W 125, S 1, N 1, R 0, PAYLOAD false, ANALYSIS 0)
MainClickDUT     -> EtherRewrite(SRC 90:e2:ba:5e:73:6c, DST 90:e2:ba:5e:73:20)
MainClickDUT     -> output;
MainClickDUT }
MainClickDUT td0 :: ToDPDKDevice(PORT $iface, VERBOSE $verbose, BLOCKING 0);
MainClickDUT
MainClickDUT fd0 :: FromDPDKDevice(PORT $iface, N_QUEUES $queuesNb, NUMA $numa, THREADOFFSET 0, MINTHREADS $threadsNb, MAXTHREADS $threadsNb, VERBOSE $verbose, PAUSE none, NDESC 4096, RSS_AGGREGATE 1, PROMISC true, PAINT_QUEUE true, BURST 32, MAX_RSS 1);
MainClickDUT
MainClickDUT
MainClickDUT fd0
MainClickDUT //    -> Print(FD0, -1)
MainClickDUT
MainClickDUT  //!Keep in sync with pipeline
MainClickDUT     ->  ps :: PaintSwitch()[0-17] => queuecount :: {
MainClickDUT      input[23] -> q23 :: CounterMP -> [0]output;
MainClickDUT    }
MainClickDUT
MainClickDUT
MainClickDUT -> classifier :: Classifier(12/0800, -)
MainClickDUT -> Strip(14)
MainClickDUT -> check :: CheckIPHeader(VERBOSE true)
MainClickDUT // -> IPPrint(LENGTH true)
MainClickDUT -> Unstrip(14)
MainClickDUT     -> pip :: Pipeline()
MainClickDUT -> legit :: AverageCounterIMP(IGNORE 2)
MainClickDUT
MainClickDUT -> td0;
MainClickDUT
MainClickDUT dropped :: AverageCounterIMP();
MainClickDUT
MainClickDUT classifier[1] -> Print(NonIPv4) -> dropped;
MainClickDUT check[1] -> dropped;
MainClickDUT dropped -> Discard;
MainClickDUT
MainClickDUT
MainClickDUT
MainClickDUT s :: Script(
MainClickDUT TYPE ACTIVE,
MainClickDUT set RUNNING 1,
MainClickDUT     set launched 0,
MainClickDUT     set lastdrop 0,
MainClickDUT     set stime $(now),
MainClickDUT     set lasttime $stime,
MainClickDUT // Show queue statistics only if the flag is set to 1
MainClickDUT wait 5s,
MainClickDUT     label loop,
MainClickDUT     set ntime $(now),
MainClickDUT set time $(sub $ntime $stime),
MainClickDUT print "",
MainClickDUT
MainClickDUT     print "",
MainClickDUT
MainClickDUT //    read fd0.queue_count,
MainClickDUT  
MainClickDUT     print $time"-RESULT-IQUEUE-PKTS-23 "$(queuecount/q23.count), print $time"-RESULT-IQUEUE-BYTES-23 "$(queuecount/q23.byte_count), print $time"-RESULT-ICPU-23 "$(load 23),
MainClickDUT
MainClickDUT     set ncpu $(gt_vec 0.05  $(load)),
MainClickDUT     goto ctn $(eq $launched 1),
MainClickDUT     goto ctn $(eq $ncpu 0),
MainClickDUT     print "EVENT LOAD_START",
MainClickDUT     set launched 1,
MainClickDUT     print "Launching migration driver!",
MainClickDUT     write migratedrv.run 1,
MainClickDUT     label ctn,
MainClickDUT     set packets $(legit.count),
MainClickDUT     set bytes $(legit.byte_count),
MainClickDUT     set nbytes $(sub $bytes $lastbytes),
MainClickDUT     set npackets $(sub $packets $lastpackets),
MainClickDUT set diff $(sub $ntime $lasttime),
MainClickDUT     set lasttime $ntime,
MainClickDUT     print "$time-RESULT-DUTTHROUGHPUT $(div $(mul 8 $(add $nbytes $(mul $npackets 24) )) $diff)",
MainClickDUT     set lastbytes $bytes,
MainClickDUT     set lastpackets $packets,
MainClickDUT     print "$time-RESULT-LOAD $(add $(load))",
MainClickDUT     print "$time-RESULT-CPU $(div $(add $(load)) $ncpu)",
MainClickDUT     print "$time-RESULT-NCPU $ncpu",
MainClickDUT     print "$time-RESULT-MAXCPU $(count $(load))",
MainClickDUT     set drop $(fd0.hw_dropped),
MainClickDUT     print "$time-RESULT-MISSED $(sub $drop $lastdrop)",
MainClickDUT wait 1s,
MainClickDUT goto loop $(eq $RUNNING 1),
MainClickDUT );
MainClickDUT
MainClickDUT
MainClickDUT
MainClickDUT
MainClickDUT DriverManager(
MainClickDUT     read fd0.rss_reta,
MainClickDUT     print "EVENT RX_STARTED",
MainClickDUT pause,
MainClickDUT print "EVENT RX_STOPPED",
MainClickDUT print "",
MainClickDUT print "   IPv4: "$(legit.count),
MainClickDUT print "Dropped: "$(dropped.count),
MainClickDUT     print "RESULT-OUTOFORDER $(fwp.outoforder)",
MainClickDUT     print "RESULT-OUTOFORDERPC $(div $(fwp.outoforder) $(fd0.count))",
MainClickDUT     print "RESULT-FWMISSED $(fd0.hw_dropped)",
MainClickDUT     print "RESULT-FWMISSEDPC $(div $(fd0.hw_dropped) $(add $(fd0.hw_dropped) $(fd0.hw_count)))",
MainClickDUT     print "RESULT-FWDROPPED $(dropped.count)",
MainClickDUT     print "RESULT-FWTHROUGHPUT $(legit.link_rate)",
MainClickDUT     print "RESULT-FWDISAPEAR $(sub $(fd0.count) $(legit.count))",
MainClickDUT     print "RESULT-FWHWDISAPEAR $(sub $(fd0.hw_count) $(legit.count))",
MainClickDUT     read fd0.xstats,
MainClickDUT     read balancer.run_stats,
MainClickDUT     print "RESULT-RUN-IMB $(balancer.run_stats_imbalance_first)",
MainClickDUT     print "RESULT-RUN-TIME $(balancer.run_stats_time_first)",
MainClickDUT print "   Sent: "$(td0.count),
MainClickDUT     read useful_kcycles,
MainClickDUT     set cycles $(add $(useful_kcycles)),
MainClickDUT     print "RESULT-KCYCLES $cycles",
MainClickDUT     print "RESULT-KCYCLESPP $(div $cycles $(td0.count))",
MainClickDUT     print "RESULT-ACYCLES $(pip/wp.cycles_per_work)",
MainClickDUT     print "RESULT-RSSSIZE $(fd0.rss_reta_size)",
MainClickDUT stop
MainClickDUT );
MainClickDUT
MainClickDUT StaticThreadSched(r 35)
MainClickDUT StaticThreadSched(s 35)
MainClickDUT Executing click at path /home/zli/npf/build/rsspp/bin//click
MainClickDUT EAL: Detected 24 lcore(s)
MainClickDUT EAL: Detected 2 NUMA nodes
MainClickDUT EAL: invalid core list, please check core numbers are in [0, 23] range
MainClickDUT
MainClickDUT Usage: click [options]
MainClickDUT
MainClickDUT EAL common options:
MainClickDUT   -c COREMASK         Hexadecimal bitmask of cores to run on
MainClickDUT   -l CORELIST         List of cores to run on
MainClickDUT                       The argument format is <c1>[-c2][,c3[-c4],...]
MainClickDUT                       where c1, c2, etc are core indexes between 0 and 128
MainClickDUT   --lcores COREMAP    Map lcore set to physical cpu set
MainClickDUT                       The argument format is
MainClickDUT                             '<lcores[@cpus]>[<,lcores[@cpus]>...]'
MainClickDUT                       lcores and cpus list are grouped by '(' and ')'
MainClickDUT                       Within the group, '-' is used for range separator,
MainClickDUT                       ',' is used for single number separator.
MainClickDUT                       '( )' can be omitted for single element group,
MainClickDUT                       '@' can be omitted if cpus and lcores have the same value
MainClickDUT   -s SERVICE COREMASK Hexadecimal bitmask of cores to be used as service cores
MainClickDUT   --master-lcore ID   Core ID that is used as master
MainClickDUT   --mbuf-pool-ops-name Pool ops name for mbuf to use
MainClickDUT   -n CHANNELS         Number of memory channels
MainClickDUT   -m MB               Memory to allocate (see also --socket-mem)
MainClickDUT   -r RANKS            Force number of memory ranks (don't detect)
MainClickDUT   -b, --pci-blacklist Add a PCI device in black list.
MainClickDUT                       Prevent EAL from using this PCI device. The argument
MainClickDUT                       format is <domain:bus:devid.func>.
MainClickDUT   -w, --pci-whitelist Add a PCI device in white list.
MainClickDUT                       Only use the specified PCI devices. The argument format
MainClickDUT                       is <[domain:]bus:devid.func>. This option can be present
MainClickDUT                       several times (once per device).
MainClickDUT                       [NOTE: PCI whitelist cannot be used with -b option]
MainClickDUT   --vdev              Add a virtual device.
MainClickDUT                       The argument format is <driver><id>[,key=val,...]
MainClickDUT                       (ex: --vdev=net_pcap0,iface=eth2).
MainClickDUT   --iova-mode   Set IOVA mode. 'pa' for IOVA_PA
MainClickDUT                       'va' for IOVA_VA
MainClickDUT   -d LIB.so|DIR       Add a driver or driver directory
MainClickDUT                       (can be used multiple times)
MainClickDUT   --vmware-tsc-map    Use VMware TSC map instead of native RDTSC
MainClickDUT   --proc-type         Type of this process (primary|secondary|auto)
MainClickDUT   --syslog            Set syslog facility
MainClickDUT   --log-level=<int>   Set global log level
MainClickDUT   --log-level=<type-match>:<int>
MainClickDUT                       Set specific log level
MainClickDUT   -v                  Display version information on startup
MainClickDUT   -h, --help          This help
MainClickDUT   --in-memory   Operate entirely in memory. This will
MainClickDUT                       disable secondary process support
MainClickDUT
MainClickDUT EAL options for DEBUG use only:
MainClickDUT   --huge-unlink       Unlink hugepage files after init
MainClickDUT   --no-huge           Use malloc instead of hugetlbfs
MainClickDUT   --no-pci            Disable PCI
MainClickDUT   --no-hpet           Disable HPET
MainClickDUT   --no-shconf         No shared config (mmap'd files)
MainClickDUT
MainClickDUT EAL Linux options:
MainClickDUT   --socket-mem        Memory to allocate on sockets (comma separated values)
MainClickDUT   --socket-limit      Limit memory allocation on sockets (comma separated values)
MainClickDUT   --huge-dir          Directory where hugetlbfs is mounted
MainClickDUT   --file-prefix       Prefix for hugepage filenames
MainClickDUT   --base-virtaddr     Base virtual address
MainClickDUT   --create-uio-dev    Create /dev/uioX (usually done by hotplug)
MainClickDUT   --vfio-intr         Interrupt mode for VFIO (legacy|msi|msix)
MainClickDUT   --legacy-mem        Legacy memory mode (no dynamic allocation, contiguous segments)
MainClickDUT   --single-file-segments Put all hugepage memory in single files
MainClickDUT   --match-allocations Free hugepages exactly as allocated
MainClickDUT
MainClickDUT EAL: FATAL: Invalid 'command line' arguments.
MainClickDUT EAL: Invalid 'command line' arguments.
MainClickDUT EAL: Error - exiting with code: 1
MainClickDUT   Cause: Click was built with DPDK support but there was an
MainClickDUT           error parsing the EAL arguments.
MainClickDUT Finished with code 1
Bad return code (1) for script 0 on p ! Something probably went wrong...
stderr:

[ERROR] A critical script failed ! Results will be ignored
Bad return code (1) for script MainClickDUT on p ! Something probably went wrong...
stderr:

BLOCKING = 0, BTHREAD = 34, GEN_NOREWRITE_ETHER = 1, LINUX_PATH = ~/workspace/linux-5.1/, MONTHREAD = 35, NDESC = 4096, PAUSE = none, PIPELINE = 0, REPORT_PERIOD = 1, SINGLEDESC = 4096, END_AFTER = 0, FORCE_LEN = 0, RX_PORT = 80, SCRIPT_ELEMENT = s, STOP_AT_TRACE = 0, fw_rules_file = /includes/ipfilter/morning-single-rules-20000.rules, trace = /home/zli/traces/maccdc2011_00013_20110312202724.pcap, CLIENT_NIC = 0, GEN_DESC = 4096, GEN_RATE = -1, GEN_THREADS = 4, IGNORE = 0, ITERATION_TIME = 0, LATENCYDUMP = /tmp/latency.csv, LIMIT = 200000000, LIMIT_TIME = 70, NIC = 0, PKTGEN_BURST_OUT = 32, PROMISC = true, R4 = 15, RCV_NIC = 0, AUTOSCALE = false, BALANCE_PERIOD = 500, CYCLES = cycles, DOMARK = true, FMARK = true, HAVE_TIMING_FNT = 2, METRONTARGET = load, QUEUE = 1, RETA_SIZE = 512, TARGETMETHOD = rss, TIMING = 1, VMARK = true, WBASE = 1000 [run 1/3 for test 1/24]
p [0] bash: line 2: cd: /home/zli/workspace/linux-5.1/tools/power/cpupower/: No such file or directory
MainClickDUT Launching client RSS_IO rx-none.click rx-process.click PARALLEL_PROCESSER DEV_READ
MainClickDUT click: no process found
MainClickDUT
MainClickDUT DPDKInfo(100000);
MainClickDUT define(
MainClickDUT $iface      0000:03:00.0,
MainClickDUT     $dispatcherNb 1,
......(There are many similar content like above repeated, so I won't list them in full here.)

**Comment by tbarbette** [comment] 2020-04-20 13:23
Forget my e-mail (but I do provide a few insightful comments), the problem is there: https://github.com/rsspp/experiments/blob/79618b0addda853b43587b3f54bf28c661adba2a/dpdk.testie#L396
I hardcoded the number of CPU cores... Change 35 to 23 for now. I'll fix that later.

**Comment by tbarbette** [comment] 2020-04-24 09:33
Ok that problem is cleanly fixed now ;)

**Closed by tbarbette** 2020-04-24 09:33 UTC
